// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	dto "github.com/duylamasd/hotels-merge/sqlc/dto"
	"github.com/jackc/pgx/v5/pgtype"
)

type Hotel struct {
	ID                int32               `json:"id"`
	HotelID           string              `json:"hotel_id"`
	DestinationID     string              `json:"destination_id"`
	Name              string              `json:"name"`
	Location          *dto.HotelLocation  `json:"location"`
	Description       *string             `json:"description"`
	Images            *dto.HotelImages    `json:"images"`
	Amenities         *dto.HotelAmenities `json:"amenities"`
	BookingConditions []string            `json:"booking_conditions"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
}
