// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	FindHotelByHotelID(ctx context.Context, hotelID string) (*Hotel, error)
	FindHotelsByDestinationAndHotelIDs(ctx context.Context, arg FindHotelsByDestinationAndHotelIDsParams) ([]*Hotel, error)
	FindHotelsByDestinationID(ctx context.Context, destinationID string) ([]*Hotel, error)
	FindHotelsByHotelIDs(ctx context.Context, hotelIds []string) ([]*Hotel, error)
}

var _ Querier = (*Queries)(nil)
